version: '3.3'
services:
    openelisglobal:
        image: openelisglobal
        network_mode: host
        restart: always
        environment:
#context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -DOE_DB_URL=jdbc:postgresql://localhost:5432/clinlims -DOE_DB_USERNAME=clinlims
        secrets:
            - source: tomcat_cert.crt
            - source: tomcat_cert.key
#this will be read into CATALINA_OPTS in docker-entrypoint.sh
            - source: OE_DB_USER_PASSWORD

secrets:
  OE_DB_USER_PASSWORD:
    file: ~/secrets/OE_DB_USER_PASSWORD
  tomcat_cert.crt:
    file: /etc/tomcat/ssl/certs/tomcat_cert.crt
  tomcat_cert.key:
    file: /etc/tomcat/ssl/private/tomcat_cert.key