version: '3.3'
services:

    database:
        container_name: openelisglobal-database
        image: postgres:9.5
        restart: always
        volumes:
              #preserves the database between containers
            - /var/lib/OpenELIS-Global/database:/var/lib/postgresql/data                
              #files here will run on install
            - /usr/OpenELIS-Global/databaseInitScripts/:/docker-entrypoint-initdb.d    
              #second value must match value in createDB.sh
            - /usr/OpenELIS-Global/database/:/database                                 
              #values must match values in DatabaseBackup.pl
            - /var/lib/OpenELIS-Global/backups/:/backups      
            
    openelisglobal:
        container_name: openelisglobal-webapp
        image: openelisglobal
        depends_on:
            - database
        ports:
            - "8080:8080"
            - "8443:8443"
        restart: always
        environment:
              #context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -DOE_DB_URL=jdbc:postgresql://database:5432/clinlims -DOE_DB_USERNAME=clinlims
        secrets:
            - source: tomcat_cert.crt
            - source: tomcat_cert.key
              #this will be read into CATALINA_OPTS in docker-entrypoint.sh
            - source: OE_DB_USER_PASSWORD
            
secrets:
  OE_DB_USER_PASSWORD:
    file: /usr/OpenELIS-Global/secrets/OE_DB_USER_PASSWORD
  tomcat_cert.crt:
    file: /etc/tomcat/ssl/certs/tomcat_cert.crt
  tomcat_cert.key:
    file: /etc/tomcat/ssl/private/tomcat_cert.key