version: '3.3'

services:
    database:
        container_name: openelisglobal-database 
        image: postgres:9.5
        ports:
            - "15432:5432"
        env_file:
            - ./dev/database/database.env
        volumes:
              # preserves the database between containers
            - db-data:/var/lib/postgresql/data                
              # files here will run on install
            - ./dev/database/dbInit:/docker-entrypoint-initdb.d
            
    oe.openelisci.org:
        container_name: openelisglobal-webapp 
        image: openelisglobal
        depends_on:
            - database
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
              # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://database:5432/clinlims?currentSchema=clinlims -Ddatasource.username=clinlims -Ddatasource.password=clinlims
        volumes:
            - ./dev/plugins:/var/lib/openelis-global/plugins
            - ./dev/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
        secrets:
            - source: keystore
            - source: truststore
            
            
volumes:
  db-data:            
secrets:
  keystore:
    file: ./dev/https/oe_selfsigned.keystore
  truststore:
    file: ./dev/https/oe_selfsigned.truststore
    