site_name: OpenELIS Global Documentation
nav:
    - Home: index.md
    - About: about.md
    - Install OpenELIS Global: install.md
    - Analyzers: analyzer.md
    - Deploy:
       - OpenMRS Interoperability: deployomrs.md 
    - Develop: dev.md
    - Website: http://openelis-global.org
theme: readthedocs

