site_name: OpenELIS Global Documentation
nav:
    - Home: index.md
    - About: about.md
    - Install OpenELIS Global: install.md
    - Analyzers: analyzer.md
    - Deploy:
       - OpenMRS Interoperability: deployomrs.md
       - Backup Script Configuration: backups.md
       - Update From OpenELIS Global 1.x to 2.x: upgrade1to2.md
    - Develop: dev.md
    - Website: http://openelis-global.org
theme: readthedocs

